# Generated by Django 4.1.3 on 2022-12-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_news_app', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('moderate_articles', 'Право модерировать статьи'),), 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='sports_news_app.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sports_news_app.tag'),
        ),
    ]
