# Generated by Django 4.1.7 on 2023-02-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sports_news_app", "0007_alter_author_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="sports_news_app.tag"
            ),
        ),
    ]
